# Generated by Django 4.1.4 on 2022-12-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_historicaluser_image_remove_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='last_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Apellidos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Nombres'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Apellidos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Nombres'),
            preserve_default=False,
        ),
    ]
